name: production workflow
on: [push]
jobs:
  tests:
    runs-on: [self-hosted, linux]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
      - name: Composer install
        run: composer install -n --prefer-dist
#      - name: Prepare Laravel Application
#        run: |
#          cp .env.ci .env
#          php artisan key:generate
      - name: Run tests
        run: php artisan test
  build:
    runs-on: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    steps:
      - name: setup node 20
        uses: actions/setup-node@v4
        with:
          node-verison: 20
          cache: npm
      - name: clean install
        run: npm ci
